//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDC.OutlookExtender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class ComposeRibbon : global::System.Configuration.ApplicationSettingsBase {
        
        private static ComposeRibbon defaultInstance = ((ComposeRibbon)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ComposeRibbon())));
        
        public static ComposeRibbon Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"You are an AI assistant that helps review text. You are assisting {userName}.
You will receive some text and make recommendations to make it:
-Kinder and more respectful in tone.
-More neutral and less aggressive.
-Emotionally intelligent and considerate.
Do not change the core message or intent. Keep the content accurate and relevant.
Then, provide:
The improved version of the text
A list of key changes you made, explaining briefly how each one made the tone more appropriate")]
        public string MakeNicer {
            get {
                return ((string)(this["MakeNicer"]));
            }
            set {
                this["MakeNicer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"You are an AI assistant that helps review text. You are assisting {userName}.
You will receive some text and make recommendations to make it:
-Simpler and easier to understand.
-More professional in tone.
-Grammatically correct and well-written.
-Clear and concise.
Do not change the meaning. Retain the original intent and key information.
Then, provide:
The improved version of the text
A list of the key changes you made, explaining briefly why each change was made.")]
        public string Improve {
            get {
                return ((string)(this["Improve"]));
            }
            set {
                this["Improve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"You are an AI assistant that helps compose emails. You are assisting {userName}. 
You will receive some text and make the necessary corrections by correcting any spelling errors.  
After the corrections, summarize all the errors found.  
Don't use introductions. Just write the modified text.")]
        public string Correct {
            get {
                return ((string)(this["Correct"]));
            }
            set {
                this["Correct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You are an AI assistant that helps compose emails. You are assisting {userName}, " +
            "and ECDC employee")]
        public string Prompt {
            get {
                return ((string)(this["Prompt"]));
            }
            set {
                this["Prompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You are an AI assistant that helps compose emails. You are assisting {userName}. " +
            "You will receive some text and provide a translation to {instructions}. ")]
        public string Translate {
            get {
                return ((string)(this["Translate"]));
            }
            set {
                this["Translate"] = value;
            }
        }
    }
}
