//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDC.OutlookExtender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class DataFlows : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataFlows defaultInstance = ((DataFlows)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataFlows())));
        
        public static DataFlows Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An unexpected error happend to OutlookExtender.\r\n\r\nLog files can be found here: {" +
            "FilePath}\r\nDo you want to report the error details:\r\n{ErrorDetails}")]
        public string ExceptionMessage {
            get {
                return ((string)(this["ExceptionMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acme@acme.com")]
        public string ExceptionNotificationEmail {
            get {
                return ((string)(this["ExceptionNotificationEmail"]));
            }
        }
    }
}
