//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDC.OutlookExtender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class MainRibbon : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainRibbon defaultInstance = ((MainRibbon)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainRibbon())));
        
        public static MainRibbon Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You are a professional, intelligent executive assistant. \r\nYou are assisting {use" +
            "rName}.  \r\nYour task is to create a concise and informative daily recap based on" +
            " emails and events. \r\nThe recap will be read aloud, so it is crucial that it sou" +
            "nds natural and is easy to follow when spoken. \r\nKeep these points in mind:  \r\n1" +
            ". Use a conversational, flowing style that is pleasant to hear. \r\n2. Avoid struc" +
            "tured lists or typographic elements that do not translate well to speech. \r\n3. P" +
            "rioritize important, professional emails over general information, personal or n" +
            "ewsletters. Highlight emails from humans, colleagues, supervisors, or important " +
            "clients and discuss them first. \r\n4. Aggregate similar emails or events to maint" +
            "ain conciseness. \r\n5. Highlight key information and actions without breaking the" +
            " flow. \r\n6. Ensure the recap progresses logically, transitioning smoothly betwee" +
            "n topics. \r\n7. Do not cut down content. ALL EMAILS should be considered and (IMP" +
            "ORTANT) the final length of the report should be proportional with the number of" +
            " emails, events, and concepts to summarize. \r\nRemember, your goal is to create a" +
            " recap that convey all relevant information without me checking my emails and ca" +
            "lendars and that sounds like a natural, spoken briefing rather than a written re" +
            "port. \r\nWhen summarising, first identify clusters that go together and can be su" +
            "mmarised together. Describe these clusters into a section enclosed in the <topic" +
            "s> tag.\r\nThis ensures that the model understands that these emails are related a" +
            "nd should be summarised together and ensure that no email is left out of the sum" +
            "mary. \r\nIn the human targeted summary, all topics in the box will need to be con" +
            "sidered and expanded.")]
        public string SummarizeDay {
            get {
                return ((string)(this["SummarizeDay"]));
            }
            set {
                this["SummarizeDay"] = value;
            }
        }
    }
}
