//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDC.OutlookExtender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Security : global::System.Configuration.ApplicationSettingsBase {
        
        private static Security defaultInstance = ((Security)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Security())));
        
        public static Security Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ECDCNET")]
        public string UserDomain {
            get {
                return ((string)(this["UserDomain"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You do not belong to a valid user domain. The application will not work")]
        public string Message {
            get {
                return ((string)(this["Message"]));
            }
            set {
                this["Message"] = value;
            }
        }
    }
}
